version: 2
jobs:
  build:
    working_directory: ~/sapic
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v2-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-node-{{ .Branch }}-
            - v2-node-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules cache
          key: v2-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run: rm -rf out
      - run: mkdir out
      - run: CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM} /usr/local/bin/yarn build
      - run: 
          command: scp -r ./* circleci@35.188.219.150:~/www:
          working_directory: ~/sapic/out

workflows:
  version: 2
  build:
    jobs:
      - build
