name: Deploy docker

on:
  push:
    branches:
      - master


jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build . -t sapic/sapic
      - name: Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Push
        run: docker push sapic/sapic
